const ERROR_CODES = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  TOKEN_IS_REQUIRED: "TOKEN_IS_REQUIRED",
  INVALID_TOKEN: "INVALID_TOKEN",
  YOU_ARE_NOT_USER: "YOU_ARE_NOT_USER",
  YOU_HAVE_BEEN_LOGGED_OUT: "YOU_HAVE_BEEN_LOGGED_OUT",
  YOU_ARE_DELETED: "YOU_ARE_DELETED",
  YOU_ARE_NOT_ACTIVE: "YOU_ARE_NOT_ACTIVE",
  ERROR_WHILE_GENERATING_TEMPLATE: "ERROR_WHILE_GENERATING_TEMPLATE",
  ERROR_IN_SEND_MAIL: "ERROR_IN_SEND_MAIL",
  INVALID_EMAIL: "INVALID_EMAIL",
  INVALID_PASSWORD: "INVALID_PASSWORD",
  EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
  INVALID_CURRENT_PASSWORD: "INVALID_CURRENT_PASSWORD",
  INVALID_ID: "INVALID_ID",
  CANNOT_DELETE_SELF: "CANNOT_DELETE_SELF",
  INVALID_OTP: "INVALID_OTP",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  SAME_PASSWORD: "SAME_PASSWORD",
  INVALID_REFERRAL_LINK: "INVALID_REFERRAL_LINK",
};

module.exports = { ERROR_CODES };
